apiVersion: v1
kind: ConfigMap
metadata:
  name: ecommerce-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "ecommerce-chart.labels" . | nindent 4 }}
data:
  ASPNETCORE_ENVIRONMENT: {{ .Values.config.aspnetcoreEnvironment | quote }}
  Cors__AllowedOrigin: {{ .Values.config.corsAllowedOrigin | quote }}
  Jwt__Issuer: {{ .Values.config.jwtIssuer | quote }}
  Jwt__Audience: {{ .Values.config.jwtAudience | quote }}
  API_URL: {{ .Values.config.apiUrl | quote }}